# Generated by Django 5.1 on 2024-09-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
