# Generated by Django 5.1 on 2024-09-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='description',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='topic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
